"""Rewrites train_kaggle.ipynb with packed training, lower LR, step checkpoints,
tokenizer always saved alongside model weights."""

import json
import os

NB_PATH = os.path.normpath(
    os.path.join(os.path.dirname(__file__), '..', 'notebooks', 'train_kaggle.ipynb')
)

with open(NB_PATH) as f:
    nb = json.load(f)


def code_cell(src: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": src.strip(),
    }


# ─── Cell 4: Config ────────────────────────────────────────────────────────────
CELL_CONFIG = (
    "# -- 4. Config --\n"
    "# Add GENIUS_TOKEN and HF_TOKEN as Kaggle Secrets (eye icon, left sidebar)\n"
    "\n"
    "import os\n"
    "from kaggle_secrets import UserSecretsClient\n"
    "secrets = UserSecretsClient()\n"
    "\n"
    "GENIUS_TOKEN = secrets.get_secret('GENIUS_TOKEN')\n"
    "HF_TOKEN     = secrets.get_secret('HF_TOKEN')\n"
    "\n"
    "os.environ['GENIUS_TOKEN']            = GENIUS_TOKEN\n"
    "os.environ['HUGGING_FACE_HUB_TOKEN'] = HF_TOKEN\n"
    "\n"
    "import torch\n"
    "total_vram = sum(\n"
    "    torch.cuda.get_device_properties(i).total_memory / 1e9\n"
    "    for i in range(torch.cuda.device_count())\n"
    ")\n"
    "\n"
    "USE_4BIT      = total_vram < 20          # False on T4 x2 (32 GB)\n"
    "MUSICGEN_SIZE = 'large' if total_vram >= 20 else 'small'\n"
    "LORA_RANK     = 64  if total_vram >= 20 else 32\n"
    "BATCH_SIZE    = 4   if total_vram >= 20 else 2\n"
    "GRAD_ACCUM    = 4   if total_vram >= 20 else 8   # eff batch = 16\n"
    "\n"
    "# v0.1 matches checkpoint vocab -- NOT Instruct, avoids format conflicts\n"
    "BASE_MODEL = 'mistralai/Mistral-7B-v0.1'\n"
    "\n"
    "GENRE         = 'trap'\n"
    "NUM_EPOCHS    = 10        # up from 3 -> ~10k steps on 5k songs\n"
    "LR            = 5e-5     # down from 2e-4 -> stable convergence, less forgetting\n"
    "MAX_LENGTH    = 512      # packed context window per chunk\n"
    "SAVE_STEPS    = 500      # step-based checkpoint\n"
    "SAMPLE_STEPS  = 500      # print generation sample every N steps\n"
    "MAX_PER_ARTIST = 5\n"
    "\n"
    "CHECKPOINT_DIR    = f'/kaggle/working/checkpoints/{GENRE}'\n"
    "DATA_PATH         = f'data/raw/{GENRE}.jsonl'\n"
    "VIRAL_VECTOR_PATH = 'data/viral_vector.npy'\n"
    "TRAINING_MODE     = 'ccl'\n"
    "\n"
    "MAX_SONGS_PER_ARTIST = 50\n"
    "SCRAPE_CHARTS        = True\n"
    "HF_DATASET_REPO      = 'SMXFREEZE/lyric-engine-data'\n"
    "\n"
    "os.makedirs(CHECKPOINT_DIR, exist_ok=True)\n"
    "\n"
    "print(f'Base model    : {BASE_MODEL}')\n"
    "print(f'Genre         : {GENRE}')\n"
    "print(f'Total VRAM    : {total_vram:.1f} GB')\n"
    "print(f'4-bit quant   : {USE_4BIT}')\n"
    "print(f'LoRA rank     : {LORA_RANK}')\n"
    "print(f'Eff. batch    : {BATCH_SIZE * GRAD_ACCUM}')\n"
    "print(f'Epochs        : {NUM_EPOCHS}')\n"
    "print(f'LR            : {LR}')\n"
    "print(f'Save every    : {SAVE_STEPS} steps')\n"
    "print(f'Sample every  : {SAMPLE_STEPS} steps')\n"
    "print('Genius token  :', 'ok' if GENIUS_TOKEN else 'MISSING')\n"
    "print('HF token      :', 'ok' if HF_TOKEN else 'MISSING')\n"
)

# ─── Cell 9: Load model ────────────────────────────────────────────────────────
CELL_MODEL = (
    "# -- 9. Load base model + LoRA --\n"
    "# modules_to_save=['embed_tokens','lm_head'] saves the resized embeddings\n"
    "# in every checkpoint, fixing vocab mismatch at inference.\n"
    "\n"
    "import torch\n"
    "from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig\n"
    "from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training\n"
    "\n"
    "tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL, use_fast=False)\n"
    "tokenizer.pad_token = tokenizer.eos_token\n"
    "tokenizer.padding_side = 'right'\n"
    "\n"
    "from configs.genres import SPECIAL_TOKENS\n"
    "num_added = tokenizer.add_special_tokens({'additional_special_tokens': SPECIAL_TOKENS})\n"
    "print(f'Special tokens added: {num_added}  (vocab size now: {len(tokenizer)})')\n"
    "\n"
    "bnb_cfg = BitsAndBytesConfig(\n"
    "    load_in_4bit=True,\n"
    "    bnb_4bit_quant_type='nf4',\n"
    "    bnb_4bit_use_double_quant=True,\n"
    "    bnb_4bit_compute_dtype=torch.bfloat16,\n"
    ") if USE_4BIT else None\n"
    "\n"
    "model = AutoModelForCausalLM.from_pretrained(\n"
    "    BASE_MODEL,\n"
    "    quantization_config=bnb_cfg,\n"
    "    torch_dtype=None if USE_4BIT else torch.float16,\n"
    "    device_map='auto',\n"
    "    low_cpu_mem_usage=True,\n"
    ")\n"
    "\n"
    "model.resize_token_embeddings(len(tokenizer))\n"
    "print(f'Embeddings resized to: {len(tokenizer)}')\n"
    "\n"
    "if USE_4BIT:\n"
    "    model = prepare_model_for_kbit_training(model, use_gradient_checkpointing=True)\n"
    "\n"
    "lora_cfg = LoraConfig(\n"
    "    r=LORA_RANK,\n"
    "    lora_alpha=LORA_RANK * 2,\n"
    "    target_modules=['q_proj', 'k_proj', 'v_proj', 'o_proj',\n"
    "                    'gate_proj', 'up_proj', 'down_proj'],\n"
    "    lora_dropout=0.05,\n"
    "    bias='none',\n"
    "    task_type='CAUSAL_LM',\n"
    "    # Saves resized embed_tokens + lm_head -- fixes inference vocab mismatch\n"
    "    modules_to_save=['embed_tokens', 'lm_head'],\n"
    ")\n"
    "model = get_peft_model(model, lora_cfg)\n"
    "model.print_trainable_parameters()\n"
    "\n"
    "for i in range(torch.cuda.device_count()):\n"
    "    used_gb  = torch.cuda.memory_allocated(i) / 1e9\n"
    "    total_gb = torch.cuda.get_device_properties(i).total_memory / 1e9\n"
    "    print(f'  GPU {i}: {used_gb:.1f}/{total_gb:.1f} GB')\n"
    "\n"
    "print('\\nModel ready.')\n"
)

# ─── Cell 10: Training ─────────────────────────────────────────────────────────
CELL_TRAIN = (
    "# -- 10. Train: packed sequences + step checkpoints + tokenizer saving --\n"
    "# PackedLyricsDataset concatenates songs end-to-end into MAX_LENGTH chunks.\n"
    "# Zero padding -> ~3x more signal per GPU step.\n"
    "# Tokenizer saved alongside model at every checkpoint.\n"
    "\n"
    "import os, json, math, time\n"
    "import torch\n"
    "from torch.utils.data import Dataset, DataLoader\n"
    "from torch.optim import AdamW\n"
    "from transformers import get_cosine_schedule_with_warmup\n"
    "\n"
    "\n"
    "class PackedLyricsDataset(Dataset):\n"
    "    def __init__(self, data_path, tokenizer, max_length, max_per_artist=None):\n"
    "        self.max_length = max_length\n"
    "        self.chunks = []\n"
    "\n"
    "        records = []\n"
    "        with open(data_path) as f:\n"
    "            for line in f:\n"
    "                line = line.strip()\n"
    "                if line:\n"
    "                    records.append(json.loads(line))\n"
    "        print(f'Loaded {len(records)} records')\n"
    "\n"
    "        if max_per_artist:\n"
    "            from collections import Counter\n"
    "            counts = Counter()\n"
    "            filtered = []\n"
    "            for r in records:\n"
    "                artist = r.get('artist', 'unknown')\n"
    "                if counts[artist] < max_per_artist:\n"
    "                    filtered.append(r)\n"
    "                    counts[artist] += 1\n"
    "            print(f'After per-artist cap: {len(filtered)} records')\n"
    "            records = filtered\n"
    "\n"
    "        eos = tokenizer.eos_token_id\n"
    "        buf = []\n"
    "        for r in records:\n"
    "            text = r.get('text') or r.get('lyrics') or ''\n"
    "            if not text.strip():\n"
    "                continue\n"
    "            buf.extend(tokenizer.encode(text, add_special_tokens=False))\n"
    "            buf.append(eos)\n"
    "\n"
    "        print(f'Token buffer: {len(buf):,} tokens')\n"
    "        for start in range(0, len(buf) - max_length, max_length):\n"
    "            self.chunks.append(buf[start : start + max_length])\n"
    "        print(f'Packed chunks: {len(self.chunks):,} x {max_length} tokens')\n"
    "\n"
    "    def __len__(self):\n"
    "        return len(self.chunks)\n"
    "\n"
    "    def __getitem__(self, idx):\n"
    "        ids = torch.tensor(self.chunks[idx], dtype=torch.long)\n"
    "        return {'input_ids': ids, 'labels': ids.clone()}\n"
    "\n"
    "\n"
    "def save_checkpoint(model, tokenizer, step, ckpt_dir):\n"
    "    path = os.path.join(ckpt_dir, f'step_{step}')\n"
    "    os.makedirs(path, exist_ok=True)\n"
    "    model.save_pretrained(path)\n"
    "    tokenizer.save_pretrained(path)   # always save tokenizer\n"
    "    print(f'  Checkpoint -> {path}')\n"
    "    return path\n"
    "\n"
    "\n"
    "def sample_generation(model, tokenizer, step, device):\n"
    "    model.eval()\n"
    "    prompt = '[GENRE:trap] [ARC:SETUP] [SECTION:VERSE]\\n'\n"
    "    ids = tokenizer.encode(prompt, return_tensors='pt').to(device)\n"
    "    with torch.no_grad():\n"
    "        out = model.generate(\n"
    "            ids, max_new_tokens=40, do_sample=True,\n"
    "            temperature=0.85, top_p=0.92, repetition_penalty=1.3,\n"
    "            pad_token_id=tokenizer.eos_token_id,\n"
    "        )\n"
    "    text = tokenizer.decode(out[0][ids.shape[-1]:], skip_special_tokens=True)\n"
    "    print(f'\\n-- Sample @ step {step} --')\n"
    "    print(text.strip() or '(empty -- model still warming up)')\n"
    "    print('-' * 40)\n"
    "    model.train()\n"
    "\n"
    "\n"
    "dataset    = PackedLyricsDataset(DATA_PATH, tokenizer, MAX_LENGTH, MAX_PER_ARTIST)\n"
    "dataloader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True,\n"
    "                        num_workers=2, pin_memory=True)\n"
    "\n"
    "optimizer    = AdamW(\n"
    "    [p for p in model.parameters() if p.requires_grad],\n"
    "    lr=LR, betas=(0.9, 0.95), weight_decay=0.01,\n"
    ")\n"
    "total_steps  = math.ceil(len(dataset) / BATCH_SIZE) * NUM_EPOCHS\n"
    "warmup_steps = min(200, total_steps // 10)\n"
    "scheduler    = get_cosine_schedule_with_warmup(optimizer, warmup_steps, total_steps)\n"
    "\n"
    "print(f'Chunks/epoch : {len(dataset):,}')\n"
    "print(f'Total steps  : {total_steps:,}')\n"
    "print(f'Warmup steps : {warmup_steps}')\n"
    "print()\n"
    "\n"
    "model.train()\n"
    "model.gradient_checkpointing_enable()\n"
    "\n"
    "device      = next(p for p in model.parameters() if p.requires_grad).device\n"
    "global_step = 0\n"
    "best_loss   = float('inf')\n"
    "best_ckpt   = None\n"
    "accum_loss  = 0.0\n"
    "optimizer.zero_grad()\n"
    "\n"
    "for epoch in range(1, NUM_EPOCHS + 1):\n"
    "    epoch_loss = 0.0\n"
    "    t0 = time.time()\n"
    "\n"
    "    for batch_idx, batch in enumerate(dataloader, 1):\n"
    "        input_ids = batch['input_ids'].to(device)\n"
    "        labels    = batch['labels'].to(device)\n"
    "\n"
    "        out  = model(input_ids=input_ids, labels=labels)\n"
    "        loss = out.loss / GRAD_ACCUM\n"
    "        loss.backward()\n"
    "        accum_loss += loss.item()\n"
    "\n"
    "        if batch_idx % GRAD_ACCUM == 0:\n"
    "            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)\n"
    "            optimizer.step()\n"
    "            scheduler.step()\n"
    "            optimizer.zero_grad()\n"
    "\n"
    "            global_step += 1\n"
    "            step_loss    = accum_loss * GRAD_ACCUM\n"
    "            accum_loss   = 0.0\n"
    "            epoch_loss  += step_loss\n"
    "\n"
    "            if global_step % 50 == 0:\n"
    "                elapsed = time.time() - t0\n"
    "                eta_min = elapsed / global_step * (total_steps - global_step) / 60\n"
    "                print(f'  ep {epoch}/{NUM_EPOCHS}  step {global_step}/{total_steps}'\n"
    "                      f'  loss {step_loss:.4f}'\n"
    "                      f'  lr {scheduler.get_last_lr()[0]:.2e}'\n"
    "                      f'  ETA {eta_min:.0f}m')\n"
    "\n"
    "            if global_step % SAMPLE_STEPS == 0:\n"
    "                sample_generation(model, tokenizer, global_step, str(device))\n"
    "\n"
    "            if global_step % SAVE_STEPS == 0:\n"
    "                ckpt = save_checkpoint(model, tokenizer, global_step, CHECKPOINT_DIR)\n"
    "                if step_loss < best_loss:\n"
    "                    best_loss = step_loss\n"
    "                    best_ckpt = ckpt\n"
    "\n"
    "    avg = epoch_loss / max(len(dataloader) // GRAD_ACCUM, 1)\n"
    "    print(f'\\n[Epoch {epoch}] avg_loss={avg:.4f}  time={(time.time()-t0)/60:.1f}m\\n')\n"
    "\n"
    "final_ckpt = save_checkpoint(model, tokenizer, global_step, CHECKPOINT_DIR)\n"
    "if not best_ckpt:\n"
    "    best_ckpt = final_ckpt\n"
    "\n"
    "print('\\nDone.')\n"
    "print(f'Best  : {best_ckpt}  (loss {best_loss:.4f})')\n"
    "print(f'Final : {final_ckpt}')\n"
)

# ─── Cell 13: Zip + download ───────────────────────────────────────────────────
CELL_ZIP = (
    "# -- 13. Package best checkpoint for download + Kaggle dataset re-upload --\n"
    "import os, zipfile\n"
    "\n"
    "print(f'Best checkpoint: {best_ckpt}')\n"
    "print()\n"
    "for fname in sorted(os.listdir(best_ckpt)):\n"
    "    sz = os.path.getsize(os.path.join(best_ckpt, fname))\n"
    "    print(f'  {fname:50s}  {sz/1e6:6.1f} MB')\n"
    "\n"
    "zip_path = f'/kaggle/working/lyric_engine_{GENRE}_best.zip'\n"
    "with zipfile.ZipFile(zip_path, 'w', compression=zipfile.ZIP_DEFLATED) as zf:\n"
    "    for fname in os.listdir(best_ckpt):\n"
    "        zf.write(os.path.join(best_ckpt, fname), fname)\n"
    "\n"
    "print(f'\\nZip: {zip_path}  ({os.path.getsize(zip_path)/1e9:.2f} GB)')\n"
    "print()\n"
    "print('Next steps:')\n"
    "print('  1. Kaggle -> Output tab -> Download the zip')\n"
    "print('  2. Unzip locally')\n"
    "print('  3. Kaggle Datasets -> Create dataset -> Upload unzipped folder')\n"
    "print('  4. run_ai_kaggle.ipynb -> Add that dataset as input')\n"
    "print()\n"
    "print('Tokenizer is inside the checkpoint -> vocab mismatch is FIXED.')\n"
)

# ─── Rebuild ───────────────────────────────────────────────────────────────────
new_cells = (
    nb["cells"][:4]
    + [code_cell(CELL_CONFIG)]
    + nb["cells"][5:9]
    + [code_cell(CELL_MODEL)]
    + [code_cell(CELL_TRAIN)]
    + nb["cells"][11:13]
    + [code_cell(CELL_ZIP)]
)

nb["cells"] = new_cells

with open(NB_PATH, "w") as f:
    json.dump(nb, f, indent=1)

print(f"Written {len(new_cells)} cells to {NB_PATH}")
